# gdb/command/transaction_command.py
from abc import ABC, abstractmethod
from typing import Optional
from gdb.domain.transaction import Transaction

class TransactionCommand(ABC):
    """Command Interface for executing financial transactions."""

    @abstractmethod
    def execute(self) -> None:
        """Execute the encapsulated transaction command."""
        pass

    @abstractmethod
    def get_transaction(self) -> Optional[Transaction]:
        """Return the transaction result generated by execution."""
        pass

    def getTransaction(self) -> Optional[Transaction]:
        return self.get_transaction()
